site_name: KONKO
site_url: https://KOUNKOLO

theme:
    name: material

markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences

nav:
 - BARA BELE BELE BA 4: lr4.md